<a href="https://colab.research.google.com/github/Sahil7151/my_data_science_project/blob/main/Suicide_Data_Filtration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("master.csv")

In [3]:
df.head(7)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
5,Albania,1987,female,75+ years,1,35600,2.81,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
6,Albania,1987,female,35-54 years,6,278800,2.15,Albania1987,NaN,"2,156,624,900",796,Silent

In [4]:
df.tail()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27816,Uzbekistan,2014,female,75+ years,9,348465,2.58,Uzbekistan2014,0.675,"63,067,077,179",2309,Silent
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27819,Uzbekistan,2014,female,55-74 years,21,1438935,1.46,Uzbekistan2014,0.675,"63,067,077,179",2309,Boomers

In [5]:
df.size

333840

In [6]:
df.shape

(27820, 12)

In [7]:
df.describe

<bound method NDFrame.describe of           country  year     sex          age  suicides_no  population  \
0         Albania  1987    male  15-24 years           21      312900
1         Albania  1987    male  35-54 years           16      308000
2         Albania  1987  female  15-24 years           14      289700
3         Albania  1987    male    75+ years            1       21800
4         Albania  1987    male  25-34 years            9      274300
...           ...   ...     ...          ...          ...         ...
27815  Uzbekistan  2014  female  35-54 years          107     3620833
27816  Uzbekistan  2014  female    75+ years            9      348465
27817  Uzbekistan  2014    male   5-14 years           60     2762158
27818  Uzbekistan  2014  female   5-14 years           44     2631600
27819  Uzbekistan  2014  female  55-74 years           21     1438935

       suicides/100k pop    country-year  HDI for year  gdp_for_year ($)   \
0                   6.71     Albania1987           NaN      2,156,624,900
1                   5.19     Albania1987           NaN      2,156,624,900
2                   4.83     Albania1987           NaN      2,156,624,900
3                   4.59     Albania1987           NaN      2,156,624,900
4                   3.28     Albania1987           NaN      2,156,624,900
...                  ...             ...           ...                ...
27815               2.96  Uzbekistan2014         0.675     63,067,077,179
27816               2.58  Uzbekistan2014         0.675     63,067,077,179
27817               2.17  Uzbekistan2014         0.675     63,067,077,179
27818               1.67  Uzbekistan2014         0.675     63,067,077,179
27819               1.46  Uzbekistan2014         0.675     63,067,077,179

       gdp_per_capita ($)       generation
0                     796     Generation X
1                     796           Silent
2                     796     Generation X
3                     796  G.I. Generation
4                     796          Boomers
...                   ...              ...
27815                2309     Generation X
27816                2309           Silent
27817                2309     Generation Z
27818                2309     Generation Z
27819                2309          Boomers

[27820 rows x 12 columns]>

In [8]:
df.describe()

,year,suicides_no,population,suicides/100k pop,HDI for year,gdp_per_capita ($)
count,27820.000000,27820.000000,2.782000e+04,27820.000000,8364.000000,27820.000000
mean,2001.258375,242.574407,1.844794e+06,12.816097,0.776601,16866.464414
std,8.469055,902.047917,3.911779e+06,18.961511,0.093367,18887.576472
min,1985.000000,0.000000,2.780000e+02,0.000000,0.483000,251.000000
25%,1995.000000,3.000000,9.749850e+04,0.920000,0.713000,3447.000000
50%,2002.000000,25.000000,4.301500e+05,5.990000,0.779000,9372.000000
75%,2008.000000,131.000000,1.486143e+06,16.620000,0.855000,24874.000000
max,2016.000000,22338.000000,4.380521e+07,224.970000,0.944000,126352.000000

In [30]:
df["country"].unique()

array(['Albania', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Barbados', 'Belarus', 'Belgium', 'Belize',
       'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Cabo Verde',
       'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Denmark', 'Dominica', 'Ecuador',
       'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia',
       'Germany', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Hungary',
       'Iceland', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Kazakhstan', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lithuania', 'Luxembourg', 'Macau', 'Maldives', 'Malta',
       'Mauritius', 'Mexico', 'Mongolia', 'Montenegro', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Norway', 'Oman', 'Panama', 'Paraguay',
       'Philippines', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar',
       'Republic of Korea', 'Romania', 'Russian Federation',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and Grenadines', 'San Marino', 'Serbia',
       'Seychelles', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa',
       'Spain', 'Sri Lanka', 'Suriname', 'Sweden', 'Switzerland',
       'Thailand', 'Trinidad and Tobago', 'Turkey', 'Turkmenistan',
       'Ukraine', 'United Arab Emirates', 'United Kingdom',
       'United States', 'Uruguay', 'Uzbekistan'], dtype=object)

In [23]:
df["country"].value_counts()

Mauritius                 382
Austria                   382
Netherlands               382
Iceland                   382
Brazil                    372
                         ...
Bosnia and Herzegovina     24
Cabo Verde                 12
Dominica                   12
Macau                      12
Mongolia                   10
Name: country, Length: 101, dtype: int64

In [24]:
df["country"].value_counts().head(10)

Mauritius      382
Austria        382
Netherlands    382
Iceland        382
Brazil         372
Singapore      372
Ecuador        372
Spain          372
Puerto Rico    372
Mexico         372
Name: country, dtype: int64

In [25]:
df["country"].value_counts().tail(10)

Nicaragua                 72
United Arab Emirates      72
Oman                      36
Saint Kitts and Nevis     36
San Marino                36
Bosnia and Herzegovina    24
Cabo Verde                12
Dominica                  12
Macau                     12
Mongolia                  10
Name: country, dtype: int64

In [19]:
jap = df[df["country"]=="Japan"]
jap

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
13364,Japan,1985,male,75+ years,1340,1791000,74.82,Japan1985,0.791,"1,398,892,744,821",12401,G.I. Generation
13365,Japan,1985,female,75+ years,1553,2862400,54.26,Japan1985,0.791,"1,398,892,744,821",12401,G.I. Generation
13366,Japan,1985,male,55-74 years,3763,8996900,41.83,Japan1985,0.791,"1,398,892,744,821",12401,G.I. Generation
13367,Japan,1985,male,35-54 years,6962,17833300,39.04,Japan1985,0.791,"1,398,892,744,821",12401,Silent
13368,Japan,1985,male,25-34 years,1982,8465800,23.41,Japan1985,0.791,"1,398,892,744,821",12401,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
13731,Japan,2015,female,35-54 years,2024,16991218,11.91,Japan2015,NaN,"4,394,977,752,878",36510,Generation X
13732,Japan,2015,female,25-34 years,685,6614211,10.36,Japan2015,NaN,"4,394,977,752,878",36510,Millenials
13733,Japan,2015,female,15-24 years,408,5772938,7.07,Japan2015,NaN,"4,394,977,752,878",36510,Millenials
13734,Japan,2015,male,5-14 years,62,5553851,1.12,Japan2015,NaN,"4,394,977,752,878",36510,Generation Z
13735,Japan,2015,female,5-14 years,28,5287719,0.53,Japan2015,NaN,"4,394,977,752,878",36510,Generation Z

In [20]:
jap.count()

country               372
year                  372
sex                   372
age                   372
suicides_no           372
population            372
suicides/100k pop     372
country-year          372
HDI for year          120
 gdp_for_year ($)     372
gdp_per_capita ($)    372
generation            372
dtype: int64

In [29]:
jap["suicides_no"].describe()

count     372.000000
mean     2169.091398
std      2170.876295
min        12.000000
25%       641.500000
50%      1641.000000
75%      2585.250000
max      8948.000000
Name: suicides_no, dtype: float64

In [38]:
df.country == "Israel"

0        False
1        False
2        False
3        False
4        False
         ...
27815    False
27816    False
27817    False
27818    False
27819    False
Name: country, Length: 27820, dtype: bool

In [39]:
df[df.country == "Israel"]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
12416,Israel,1985,male,75+ years,24,66600,36.04,Israel1985,0.768,"27,493,591,484",7325,G.I. Generation
12417,Israel,1985,male,55-74 years,48,249100,19.27,Israel1985,0.768,"27,493,591,484",7325,G.I. Generation
12418,Israel,1985,female,75+ years,10,75500,13.25,Israel1985,0.768,"27,493,591,484",7325,G.I. Generation
12419,Israel,1985,male,35-54 years,41,396400,10.34,Israel1985,0.768,"27,493,591,484",7325,Silent
12420,Israel,1985,female,55-74 years,28,290900,9.63,Israel1985,0.768,"27,493,591,484",7325,G.I. Generation
...,...,...,...,...,...,...,...,...,...,...,...,...
12783,Israel,2015,female,25-34 years,13,581972,2.23,Israel2015,NaN,"299,093,839,690",39793,Millenials
12784,Israel,2015,female,35-54 years,20,967412,2.07,Israel2015,NaN,"299,093,839,690",39793,Generation X
12785,Israel,2015,female,15-24 years,8,617440,1.30,Israel2015,NaN,"299,093,839,690",39793,Millenials
12786,Israel,2015,male,5-14 years,2,770443,0.26,Israel2015,NaN,"299,093,839,690",39793,Generation Z
12787,Israel,2015,female,5-14 years,1,733603,0.14,Israel2015,NaN,"299,093,839,690",39793,Generation Z

In [44]:
df.loc[(df.country == "Israel") & (df.year == 2015) & (df.age == "25-34 years") & (df.sex == "male"),["country","year","sex","age","suicides_no","population"]]

      country  year   sex          age  suicides_no  population
12779  Israel  2015  male  25-34 years           45      586251

In [45]:
df.loc[(df.country == "Israel") & (df.year == 2015) & (df.sex == "male"),["country","year","sex","age","suicides_no","population"]]

      country  year   sex          age  suicides_no  population
12776  Israel  2015  male    75+ years           30      168826
12777  Israel  2015  male  55-74 years           65      595247
12778  Israel  2015  male  35-54 years           92      944406
12779  Israel  2015  male  25-34 years           45      586251
12781  Israel  2015  male  15-24 years           35      644674
12786  Israel  2015  male   5-14 years            2      770443

In [56]:
df[(df.year.between(1998,2003)) & (df.country == "Panama")]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
18348,Panama,1998,male,55-74 years,21,124577,16.86,Panama1998,NaN,"11,575,486,400",4488,Silent
18349,Panama,1998,male,25-34 years,34,244555,13.90,Panama1998,NaN,"11,575,486,400",4488,Generation X
18350,Panama,1998,male,15-24 years,36,288189,12.49,Panama1998,NaN,"11,575,486,400",4488,Generation X
18351,Panama,1998,male,75+ years,3,27984,10.72,Panama1998,NaN,"11,575,486,400",4488,G.I. Generation
18352,Panama,1998,male,35-54 years,30,298156,10.06,Panama1998,NaN,"11,575,486,400",4488,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
18415,Panama,2003,female,55-74 years,2,153054,1.31,Panama2003,NaN,"13,693,981,200",4790,Silent
18416,Panama,2003,female,25-34 years,3,264433,1.13,Panama2003,NaN,"13,693,981,200",4790,Generation X
18417,Panama,2003,male,5-14 years,3,329290,0.91,Panama2003,NaN,"13,693,981,200",4790,Millenials
18418,Panama,2003,female,5-14 years,0,317030,0.00,Panama2003,NaN,"13,693,981,200",4790,Millenials
18419,Panama,2003,female,75+ years,0,39497,0.00,Panama2003,NaN,"13,693,981,200",4790,Silent

In [55]:
df.loc[(df.year.isin([1998,2003])) & (df.country == "Israel")]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
12572,Israel,1998,male,75+ years,33,103400,31.91,Israel1998,NaN,"115,979,230,547",21637,G.I. Generation
12573,Israel,1998,male,55-74 years,55,333300,16.50,Israel1998,NaN,"115,979,230,547",21637,Silent
12574,Israel,1998,female,75+ years,15,143800,10.43,Israel1998,NaN,"115,979,230,547",21637,G.I. Generation
12575,Israel,1998,male,25-34 years,42,421100,9.97,Israel1998,NaN,"115,979,230,547",21637,Generation X
12576,Israel,1998,male,15-24 years,52,534300,9.73,Israel1998,NaN,"115,979,230,547",21637,Generation X
12577,Israel,1998,male,35-54 years,55,668200,8.23,Israel1998,NaN,"115,979,230,547",21637,Boomers
12578,Israel,1998,female,55-74 years,21,403400,5.21,Israel1998,NaN,"115,979,230,547",21637,Silent
12579,Israel,1998,female,35-54 years,19,705600,2.69,Israel1998,NaN,"115,979,230,547",21637,Boomers
12580,Israel,1998,female,15-24 years,13,511000,2.54,Israel1998,NaN,"115,979,230,547",21637,Generation X
12581,Israel,1998,female,25-34 years,10,421100,2.37,Israel1998,NaN,"115,979,230,547",21637,Generation X
12582,Israel,1998,male,5-14 years,2,571700,0.35,Israel1998,NaN,"115,979,230,547",21637,Millenials
12583,Israel,1998,female,5-14 years,1,543300,0.18,Israel1998,NaN,"115,979,230,547",21637,Millenials
12632,Israel,2003,male,75+ years,28,120134,23.31,Israel2003,NaN,"126,864,966,909",21133,Silent
12633,Israel,2003,male,55-74 years,70,393481,17.79,Israel2003,NaN,"126,864,966,909",21133,Silent
12634,Israel,2003,male,35-54 years,125,739587,16.90,Israel2003,NaN,"126,864,966,909",21133,Boomers
12635,Israel,2003,male,25-34 years,57,509736,11.18,Israel2003,NaN,"126,864,966,909",21133,Generation X
12636,Israel,2003,male,15-24 years,62,566251,10.95,Israel2003,NaN,"126,864,966,909",21133,Millenials
12637,Israel,2003,female,75+ years,10,178813,5.59,Israel2003,NaN,"126,864,966,909",21133,Silent
12638,Israel,2003,female,55-74 years,24,457426,5.25,Israel2003,NaN,"126,864,966,909",21133,Silent
12639,Israel,2003,female,35-54 years,25,779552,3.21,Israel2003,NaN,"126,864,966,909",21133,Boomers
12640,Israel,2003,female,25-34 years,8,503837,1.59,Israel2003,NaN,"126,864,966,909",21133,Generation X
12641,Israel,2003,female,15-24 years,5,544294,0.92,Israel2003,NaN,"126,864,966,909",21133,Millenials
12642,Israel,2003,male,5-14 years,3,620511,0.48,Israel2003,NaN,"126,864,966,909",21133,Millenials
12643,Israel,2003,female,5-14 years,0,589505,0.00,Israel2003,NaN,"126,864,966,909",21133,Millenials

In [62]:
df.loc[~(df.year.isin([1998,2003])) & (df.country == "Qatar")]

# ~ tilt indicated excluding this

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
20052,Qatar,1995,female,15-24 years,0,24859,0.00,Qatar1995,0.783,"8,137,911,978",17559,Generation X
20053,Qatar,1995,female,25-34 years,0,36029,0.00,Qatar1995,0.783,"8,137,911,978",17559,Generation X
20054,Qatar,1995,female,35-54 years,0,39135,0.00,Qatar1995,0.783,"8,137,911,978",17559,Boomers
20055,Qatar,1995,female,5-14 years,0,43647,0.00,Qatar1995,0.783,"8,137,911,978",17559,Millenials
20056,Qatar,1995,female,55-74 years,0,5879,0.00,Qatar1995,0.783,"8,137,911,978",17559,Silent
...,...,...,...,...,...,...,...,...,...,...,...,...
20225,Qatar,2016,female,25-34 years,2,164901,1.21,Qatar2016,NaN,"152,451,923,077",62484,Millenials
20226,Qatar,2016,female,15-24 years,0,88675,0.00,Qatar2016,NaN,"152,451,923,077",62484,Millenials
20227,Qatar,2016,female,55-74 years,0,26182,0.00,Qatar2016,NaN,"152,451,923,077",62484,Boomers
20228,Qatar,2016,female,75+ years,0,3250,0.00,Qatar2016,NaN,"152,451,923,077",62484,Silent
20229,Qatar,2016,male,75+ years,0,6093,0.00,Qatar2016,NaN,"152,451,923,077",62484,Silent

In [61]:
df.loc[~(df.year.isin([1998,2003])) & (df.country == "Qatar")].year.unique()

array([1995, 2001, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016])